// @ts-nocheck
// This file is autogenerated by Firebase Studio. All changes will be overwritten.
//prettier-ignore
'use client';

import { FirebaseProvider } from './provider';

export function FirebaseClientProvider({ children }) {
  return <FirebaseProvider>{children}</FirebaseProvider>;
}
