// @ts-nocheck
// This file is autogenerated by Firebase Studio. All changes will be overwritten.
//prettier-ignore
import { FirebaseOptions } from 'firebase/app';

/**
 * The value for `NEXT_PUBLIC_FIREBASE_CONFIG` is replaced at build time by
 * the Firebase App Hosting backend with the configuration of the Firebase

 * app that this code is running in.
 *
 * This is a client-only configuration object.
 */
export const firebaseConfig: FirebaseOptions = process.env.NEXT_PUBLIC_FIREBASE_CONFIG
  ? JSON.parse(process.env.NEXT_PUBLIC_FIREBASE_CONFIG)
  : {};
