// @ts-nocheck
// This file is autogenerated by Firebase Studio. All changes will be overwritten.
//prettier-ignore
import { getAnalytics } from "firebase/analytics";
import { initializeApp, getApp, getApps, FirebaseApp } from 'firebase/app';
import { getAuth, Auth } from 'firebase/auth';
import { getFirestore, Firestore } from 'firebase/firestore';

import { firebaseConfig } from './config';

export * from './provider';

// A full list of all supported auth providers.
export const ALL_PROVIDERS = ['google', 'facebook', 'twitter', 'github', 'email', 'phone', 'anonymous'];

let app: FirebaseApp;
let auth: Auth;
let firestore: Firestore;

function initializeFirebase() {
  if (typeof window === 'undefined') {
    return null;
  }
  
  if (!getApps().length) {
    try {
      if (!firebaseConfig.apiKey) {
        console.warn("Firebase config not found. Firebase will not be initialized.");
        return null;
      }
      app = initializeApp(firebaseConfig);
      auth = getAuth(app);
      firestore = getFirestore(app);
    } catch (e) {
      console.error("Error initializing Firebase:", e);
      return null;
    }
  } else {
    app = getApp();
    auth = getAuth(app);
    firestore = getFirestore(app);
  }
  return { app, auth, firestore };
}

// Re-export initializeFirebase
export { initializeFirebase };


/**
 *
 * @returns the initialized firebase app instance.
 */
export function getFirebaseAnalytics() {
  if (typeof window === 'undefined') {
    return null;
  }
  if (!getApps().length) {
    try {
      const app = initializeApp(firebaseConfig);
      return getAnalytics(app);
    } catch (e) {
      console.error(e);
      return null;
    }
  } else {
    const app = getApp();
    return getAnalytics(app);
  }
}
