// @ts-nocheck
// This file is autogenerated by Firebase Studio. All changes will be overwritten.
//prettier-ignore
'use client';
import {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useState,
} from 'react';

import { initializeFirebase } from '.';

const FirebaseContext = createContext(null);

export const useFirebase = () => useContext(FirebaseContext);

export function FirebaseProvider({ children }) {
  const [app, setApp] = useState(null);
  const [auth, setAuth] = useState(null);
  const [firestore, setFirestore] = useState(null);
  const [isFirebaseInitialized, setIsFirebaseInitialized] = useState(false);

  useEffect(() => {
    if (isFirebaseInitialized) {
      return;
    }
    const firebaseInstances = initializeFirebase();
    if (firebaseInstances) {
      const { app: nextApp, auth: nextAuth, firestore: nextFirestore } = firebaseInstances;
      setApp(nextApp);
      setAuth(nextAuth);
      setFirestore(nextFirestore);
      setIsFirebaseInitialized(true);
    }
  }, [isFirebaseInitialized]);

  const contextValue = useMemo(
    () => ({
      app,
      auth,
      firestore,
      isFirebaseInitialized,
    }),
    [app, auth, firestore, isFirebaseInitialized],
  );

  return (
    <FirebaseContext.Provider value={contextValue}>
      {children}
    </FirebaseContext.Provider>
  );
}

export const useFirebaseApp = () => {
  return useContext(FirebaseContext)?.['app'];
};

export const useFirebaseAuth = () => {
  return useContext(FirebaseContext)?.['auth'];
};

export const useFirestore = () => {
  return useContext(FirebaseContext)?.['firestore'];
};
